CREATE TABLE PE100 
(
ID integer identity primary key,
[ANMA BOYU] float,
[ATÜ] float,
[ET KALINLIÐI EN AZ] float,
[ET KALINLIÐI EN FAZLA] float,
[MÝNÝMUM AÐIRLIK (GR/M)]  float,
[MAKSÝMUM AÐIRLIK (GR/M)]  float
)

select* FROM PE100


insert into PE100 ([ANMA BOYU],[ATÜ],[ET KALINLIÐI EN AZ],[ET KALINLIÐI EN FAZLA],[MÝNÝMUM AÐIRLIK (GR/M)],[MAKSÝMUM AÐIRLIK (GR/M)]) values(20,16,2,2.3,110,112)

insert into PE100 ([ANMA BOYU],[ATÜ],[ET KALINLIÐI EN AZ],[ET KALINLIÐI EN FAZLA],[MÝNÝMUM AÐIRLIK (GR/M)],[MAKSÝMUM AÐIRLIK (GR/M)]) values(20,20,2.3,2.7,130,133)

insert into PE100 ([ANMA BOYU],[ATÜ],[ET KALINLIÐI EN AZ],[ET KALINLIÐI EN FAZLA],[MÝNÝMUM AÐIRLIK (GR/M)],[MAKSÝMUM AÐIRLIK (GR/M)]) values(20,25,3,3.4,151,154)

insert into PE100 ([ANMA BOYU],[ATÜ],[ET KALINLIÐI EN AZ],[ET KALINLIÐI EN FAZLA],[MÝNÝMUM AÐIRLIK (GR/M)],[MAKSÝMUM AÐIRLIK (GR/M)]) values(20,32,3.4,3.9,177,180)





insert into PE100 ([ANMA BOYU],[ATÜ],[ET KALINLIÐI EN AZ],[ET KALINLIÐI EN FAZLA],[MÝNÝMUM AÐIRLIK (GR/M)],[MAKSÝMUM AÐIRLIK (GR/M)]) values(25,13,2,2.3,149,152)

insert into PE100 ([ANMA BOYU],[ATÜ],[ET KALINLIÐI EN AZ],[ET KALINLIÐI EN FAZLA],[MÝNÝMUM AÐIRLIK (GR/M)],[MAKSÝMUM AÐIRLIK (GR/M)]) values(25,16,2.3,2.7,168,171)

insert into PE100 ([ANMA BOYU],[ATÜ],[ET KALINLIÐI EN AZ],[ET KALINLIÐI EN FAZLA],[MÝNÝMUM AÐIRLIK (GR/M)],[MAKSÝMUM AÐIRLIK (GR/M)]) values(25,20,3,3.4,216,220)

insert into PE100 ([ANMA BOYU],[ATÜ],[ET KALINLIÐI EN AZ],[ET KALINLIÐI EN FAZLA],[MÝNÝMUM AÐIRLIK (GR/M)],[MAKSÝMUM AÐIRLIK (GR/M)]) values(25,25,3.5,4,235,240)


insert into PE100 ([ANMA BOYU],[ATÜ],[ET KALINLIÐI EN AZ],[ET KALINLIÐI EN FAZLA],[MÝNÝMUM AÐIRLIK (GR/M)],[MAKSÝMUM AÐIRLIK (GR/M)]) values(25,32,4.2,4.8,273,278)




